
export const workData = [
    {
        id: 1,
        title: "Portfolio",
        description: "All things related to Discord in one place. Find the best bots, servers, and communities.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/k73UnJZ.png",
        link: "https://discord.place",
        repo: false,
    },
    {
        id: 2,
        title: "Chrome Vault",
        description: "A Google Chrome extension that automatically converts prices to TRY from USD with the current exchange rate on Steam web pages.",
        tags: ["JavaScript"],
        imageUrl: "https://i.imgur.com/XXrkGOK.png",
        link: "https://github.com/chimpdev/steam-auto-try-converter",
        repo: true,
    },
    {
        id: 3,
        title: "Ip address tracker",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    },
    {
        id: 4,
        title: "Note takrr",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    },
    {
        id: 5,
        title: "the translator",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    },
    {
        id: 6,
        title: "The Weather times",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    },
    {
        id: 7,
        title: "Ip address tracker",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    },
    {
        id: 8,
        title: "Ip address tracker",
        description: "A website that allows you to download mp3 files for your Discord Soundboard.",
        tags: ["Next.js", "Express", "MongoDB"],
        imageUrl: "https://i.imgur.com/4eFt9Oz.png",
        link: "https://discordsfx.com",
        repo: false,
    }
]
